include_guard()

hunter_config(Jpeg
	URL "https://codeload.github.com/Telefrag-Software/libjpeg/zip/tags/9f"
	VERSION "9f"
	SHA1 "2f0ca550a93e9dc429dbd94b70aace53b9360bc6"
)

hunter_config(liblzma
	URL "https://codeload.github.com/tukaani-project/xz/zip/tags/v5.8.2"
	VERSION "5.8.2"
	SHA1 "078a77cfee78937449a9f159c6d35fe81806f268"
	CMAKE_ARGS
		BUILD_SHARED_LIBS=OFF
		BUILD_TESTING=OFF
		XZ_SMALL=OFF
		XZ_EXTERNAL_SHA256=OFF
		XZ_MICROLZMA_ENCODER=ON
		XZ_MICROLZMA_DECODER=ON
		XZ_LZIP_DECODER=ON
		XZ_CLMUL_CRC=ON
		XZ_ARM64_CRC32=ON
		XZ_LOONGARCH_CRC32=ON
		XZ_TOOL_XZDEC=OFF
		XZ_TOOL_LZMADEC=OFF
		XZ_TOOL_LZMAINFO=OFF
		XZ_TOOL_XZ=OFF
		XZ_TOOL_SYMLINKS=OFF
		XZ_TOOL_SYMLINKS_LZMA=OFF
		XZ_TOOL_SCRIPTS=OFF
		XZ_DOXYGEN=OFF
		XZ_DOC=OFF
)

hunter_config(WebP
	URL "https://codeload.github.com/webmproject/libwebp/zip/tags/v1.6.0"
	VERSION "1.6.0"
	SHA1 "32ca0698bf7a5cabb5f7213226c3420b8c26dfdb"
	CMAKE_ARGS
		BUILD_SHARED_LIBS=OFF
		WEBP_LINK_STATIC=ON
		WEBP_BUILD_ANIM_UTILS=OFF
		WEBP_BUILD_CWEBP=OFF
		WEBP_BUILD_DWEBP=OFF
		WEBP_BUILD_GIF2WEBP=OFF
		WEBP_BUILD_IMG2WEBP=OFF
		WEBP_BUILD_VWEBP=OFF
		WEBP_BUILD_WEBPINFO=OFF
		WEBP_BUILD_LIBWEBPMUX=ON
		WEBP_BUILD_WEBPMUX=OFF
		WEBP_BUILD_EXTRAS=OFF
		WEBP_BUILD_WEBP_JS=OFF
		WEBP_BUILD_FUZZTEST=OFF
		WEBP_USE_THREAD=ON
		WEBP_NEAR_LOSSLESS=ON
		WEBP_ENABLE_SWAP_16BIT_CSP=OFF
		WEBP_ENABLE_WUNUSED_RESULT=OFF
		WEBP_UNICODE=ON
)

hunter_config(ZLIB
	URL "https://github.com/Telefrag-Software/zlib/archive/refs/heads/hunter-1.3.1.2.zip"
	VERSION "1.3.1.2"
	SHA1 "0a8b433ea1eac928a1dfaff3f533dfba61b3aeb9"
	CMAKE_ARGS
		ZLIB_BUILD_TESTING=OFF
		ZLIB_BUILD_SHARED=OFF
		ZLIB_BUILD_STATIC=ON
		ZLIB_BUILD_MINIZIP=OFF
		ZLIB_INSTALL=ON
		ZLIB_PREFIX=OFF
		ZLIB_INSTALL_DOCS=OFF
		ZLIB_INSTALL_LICENSES=OFF
)

hunter_config(zstd
	URL "https://codeload.github.com/facebook/zstd/zip/tags/v1.5.7"
	VERSION "1.5.7.0"
	SHA1 "8bd73c3d2bf87f0c033299f5d05fb4bde2480ad1"
	CMAKE_ARGS
		ZSTD_LEGACY_SUPPORT=OFF
		ZSTD_MULTITHREAD_SUPPORT=ON
		ZSTD_BUILD_PROGRAMS=OFF
		ZSTD_BUILD_CONTRIB=OFF
		ZSTD_PROGRAMS_LINK_SHARED=OFF
		ZSTD_BUILD_TESTS=OFF
		ZSTD_USE_STATIC_RUNTIME=ON
		ZSTD_ENABLE_CXX=ON
)
